name: Run Pytest

on:
  push:
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"

      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release

      - name: Install Tesseract
        run: sudo apt-get install python3-pil tesseract-ocr libtesseract-dev tesseract-ocr-eng

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: true

      - name: Run Pytest
        run: |
          pytest tests/test_pdf_processor.py
          pytest tests/test_ocr_decorator.py